### ISSUE TITLE
fails to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [hamsterdam/kawhi#13]
```
kawhi                     > /tmp/stack-930e93223b6b89bd/kawhi-0.3.0/library/Data/NBA/Stats.hs:303:63: error:
kawhi                     >     • Couldn't match type ‘Text.Text’ with ‘Aeson.Key’
kawhi                     >       Expected: [Aeson.Pair]
kawhi                     >         Actual: [(SplitColumn, Aeson.Value)]
kawhi                     >     • In the first argument of ‘Aeson.object’, namely
kawhi                     >         ‘(zip columns row)’
kawhi                     >       In the second argument of ‘($)’, namely
kawhi                     >         ‘Aeson.object (zip columns row)’
kawhi                     >       In the expression:
kawhi                     >         Aeson.parse Aeson.parseJSON $ Aeson.object (zip columns row)
kawhi                     >     |
kawhi                     > 303 |         then case Aeson.parse Aeson.parseJSON $ Aeson.object (zip columns row) of
kawhi                     >     |                                                               ^^^^^^^^^^^^^^^
```
